-- 0004_marketdata_product_attempts.sql
--
-- MXM V1 Marketdata SQLite schema:
-- Product-level market data attempts ledger.
--
-- Purpose:
--   Record each product-level orchestrator run attempt, as an operational envelope
--   around the dataset-level orchestrators:
--     * instrument_definitions
--     * instrument_definition_mappings
--     * ohlcv_1d
--
-- Design:
--   * One row per product-level orchestrator invocation per product_id.
--   * Two-phase write:
--       - insert "running" row at start (finished_at NULL)
--       - update to terminal status at end (finished_at set)
--   * No foreign keys: do not block operational evidence capture.
--   * ISO8601Z TEXT timestamps for lexicographic sort stability.

CREATE TABLE IF NOT EXISTS marketdata_product_attempts (
    -- Primary key: UUID4 generated by orchestrator
    attempt_uid TEXT PRIMARY KEY,

    -- System timestamp for this attempt row (system time)
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),

    -- Orchestrator run metadata
    run_ts_utc  TEXT NOT NULL,               -- orchestrator report ts_utc (ISO8601Z)
    mode        TEXT NOT NULL,               -- "bootstrap" | "update"
    dry_run     INTEGER NOT NULL DEFAULT 0,  -- 0/1
    reset       INTEGER NOT NULL DEFAULT 0,  -- 0/1
    reset_local INTEGER NOT NULL DEFAULT 0,  -- 0/1

    -- Operational identity
    product_id TEXT NOT NULL,

    -- Budget accounting
    cost_cap_usd  REAL NOT NULL,
    cost_used_usd REAL NOT NULL DEFAULT 0.0,
    remaining_usd REAL NOT NULL DEFAULT 0.0,

    -- Outcome (control-plane)
    status      TEXT NOT NULL,  -- "running" | "success" | "halted" | "error"
    stop_reason TEXT,           -- nullable while running; set on terminal state

    -- Lifecycle timestamps
    started_at  TEXT NOT NULL,
    finished_at TEXT,

    -- Compact structured summary (JSON string)
    summary_json TEXT NOT NULL DEFAULT '{}',

    -- Error capture (if status="error")
    error_type    TEXT,
    error_message TEXT
);

-- Common operator query: show latest runs for a product
CREATE INDEX IF NOT EXISTS idx_md_product_attempts_product_ordering
ON marketdata_product_attempts (product_id, started_at DESC, created_at DESC);

-- Common operator query: slice by time across products
CREATE INDEX IF NOT EXISTS idx_md_product_attempts_started
ON marketdata_product_attempts (started_at DESC);

-- Common operator query: show failures quickly
CREATE INDEX IF NOT EXISTS idx_md_product_attempts_status_started
ON marketdata_product_attempts (status, started_at DESC);
