-- 0003_ohlcv_1d_attempts.sql
--
-- MXM V1 Marketdata SQLite schema:
-- OHLCV-1D ingestion attempts ledger (append-only).
--
-- Purpose:
--   Record each contract-level operational attempt (or skip decision) made by the
--   OHLCV-1D orchestrator, including:
--     * the inputs (product/contract, resolved vendor identity),
--     * the expected window surfaces (interest, dataset range, lifecycle, expected),
--     * the decision/result (status, vendor_final, cost),
--     * pre/post storage coverage snapshots (min/max/rows/path),
--     * error details for failed attempts.
--
-- Design:
--   * Append-only (no silent mutation).
--   * No foreign keys: do not block ingestion if upstream datasets are incomplete.
--   * ISO8601Z TEXT timestamps for lexicographic sort stability.
--   * A small set of indexes to support "latest attempt" and product-level ops queries.
--
-- Notes:
--   * This is an operational ledger, not a canonical truth table.
--   * It supports retry/state logic, but does not encode the state machine itself.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS ohlcv_1d_attempts (
    -- Primary key:
    --  - recommended: UUID4/ULID generated by orchestrator
    --  - alternative: deterministic sha256 if you later want idempotent attempt writes
    attempt_uid TEXT PRIMARY KEY,

    -- System timestamp for this attempt row (system time)
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),

    -- Orchestrator run metadata
    run_ts_utc TEXT NOT NULL,          -- orchestrator report ts_utc (ISO8601Z)
    mode TEXT NOT NULL,                -- "bootstrap" | "update"
    dry_run INTEGER NOT NULL DEFAULT 0, -- 0/1
    reset_local INTEGER NOT NULL DEFAULT 0, -- 0/1

    -- MXM contract identity (operational keys)
    product_id TEXT NOT NULL,
    contract_id TEXT NOT NULL,
    contract_key TEXT NOT NULL,        -- e.g. "cme_emini_snp500_futures:2017-12"

    -- Vendor identity (nullable if unmapped)
    feed TEXT,                         -- optional; if you want, set to definition feed key
    dataset TEXT,
    publisher_id INTEGER,
    instrument_id INTEGER,
    raw_symbol TEXT,

    -- Contract interest window (from refdata), half-open [start,end)
    interest_start TEXT NOT NULL,
    interest_end   TEXT NOT NULL,

    -- Dataset availability surface (from vendor dataset_range), half-open [start,end)
    dataset_start TEXT NOT NULL,
    dataset_end   TEXT NOT NULL,

    -- Lifecycle surface (from instrument_definitions), day-aligned half-open constraints
    activation_floor TEXT,             -- may be NULL if unknown
    expiration_ceiling TEXT,           -- may be NULL if unknown

    -- Expected window (intersection), half-open [start,end)
    expected_start TEXT NOT NULL,
    expected_end   TEXT NOT NULL,
    is_empty INTEGER NOT NULL DEFAULT 0, -- 0/1

    -- Diagnostics on why expected differs from interest
    is_vendor_limited INTEGER NOT NULL DEFAULT 0,     -- 0/1
    is_lifecycle_limited INTEGER NOT NULL DEFAULT 0,  -- 0/1

    -- "Vendor finality" label:
    -- True if, given available surfaces, we believe no future vendor data can extend expected_end.
    vendor_final INTEGER NOT NULL DEFAULT 0, -- 0/1

    -- Orchestrator decision/result
    status TEXT NOT NULL,
    -- status values (recommended; keep strings stable once adopted):
    --   "unmapped"
    --   "skipped_empty_expected_window"
    --   "complete"
    --   "dry_run"
    --   "skipped_cost_cap"
    --   "ingested"
    --   "incomplete"
    status_detail TEXT,                -- optional free text

    -- Cost accounting
    cost_cap_usd REAL,                 -- cap in force at the time (optional)
    cost_estimated_usd REAL,            -- estimate used to enforce cap (optional)
    cost_charged_usd REAL,              -- if you later capture actual billed cost (optional)
    cost_used_usd REAL,                 -- what we deducted from remaining budget (optional)

    -- Coverage snapshot BEFORE attempt (from store.scan_coverage)
    stored_min_before TEXT,
    stored_max_before TEXT,
    stored_rows_before INTEGER,
    bars_path_before TEXT,

    -- Coverage snapshot AFTER attempt (if any)
    stored_min_after TEXT,
    stored_max_after TEXT,
    stored_rows_after INTEGER,
    bars_path_after TEXT,

    -- Error capture (non-fatal to pipeline; do not exceed reasonable sizes)
    error_type TEXT,
    error_message TEXT
);

-- Primary operational index: latest attempts per (product_id, contract_id)
CREATE INDEX IF NOT EXISTS idx_ohlcv1d_attempts_contract_ordering
ON ohlcv_1d_attempts (product_id, contract_id, run_ts_utc, created_at);

-- Useful for vendor-side diagnosis: latest attempts per instrument identity
CREATE INDEX IF NOT EXISTS idx_ohlcv1d_attempts_vendor_ordering
ON ohlcv_1d_attempts (dataset, publisher_id, instrument_id, created_at);

-- Report-level queries: all attempts in a given orchestrator run
CREATE INDEX IF NOT EXISTS idx_ohlcv1d_attempts_run
ON ohlcv_1d_attempts (run_ts_utc, created_at);

-- Quick filtering by status for ops dashboards/diagnostics
CREATE INDEX IF NOT EXISTS idx_ohlcv1d_attempts_status
ON ohlcv_1d_attempts (status, created_at);
